// src/main/webapp/app/modules/administration/logs/logs.tsx
import React, { useState, useEffect } from 'react';


import { getLoggers, changeLogLevel } from '../administration.reducer';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const LogsPage = () => {
  const [filter, setFilter] = useState('');
  const logs = useAppSelector(state => state.administration.logs);
  const isFetching = useAppSelector(state => state.administration.loading);
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getLoggers());
  }, []);

  const changeLevel = (loggerName, level) => () => dispatch(changeLogLevel(loggerName, level));

  const changeFilter = evt => setFilter(evt.target.value);

  const getClassName = (level, check, className) => (level === check ? `btn btn-sm btn-${className}` : 'btn btn-sm btn-light');

  const filterFn = l => l.name.toUpperCase().includes(filter.toUpperCase());

  const loggers = logs ? Object.entries(logs.loggers).map((e: any) => ({ name: e[0], level: e[1].effectiveLevel })) : [];

  return (
    <div>
      <h2 id="logs-page-heading" data-cy="logsPageHeading">
        Logid
      </h2>
      <p>
        Kokku on {loggers.length} logijat.
      </p>

      <span>
        Filter
      </span>
      <input type="text" value={filter} onChange={changeFilter} className="form-control" disabled={isFetching} />

      <table className="table table-sm table-striped table-bordered" aria-describedby="logs-page-heading">
        <thead>
          <tr title="click to order">
            <th>
              <span>
                Nimi
              </span>
            </th>
            <th>
              <span>
                Tase
              </span>
            </th>
          </tr>
        </thead>
        <tbody>
          {loggers.filter(filterFn).map((logger, i) => (
            <tr key={`log-row-${i}`}>
              <td>
                <small>{logger.name}</small>
              </td>
              <td>
                <button
                  disabled={isFetching}
                  onClick={changeLevel(logger.name, 'TRACE')}
                  className={getClassName(logger.level, 'TRACE', 'primary')}
                >
                  TRACE
                </button>
                <button
                  disabled={isFetching}
                  onClick={changeLevel(logger.name, 'DEBUG')}
                  className={getClassName(logger.level, 'DEBUG', 'success')}
                >
                  DEBUG
                </button>
                <button
                  disabled={isFetching}
                  onClick={changeLevel(logger.name, 'INFO')}
                  className={getClassName(logger.level, 'INFO', 'info')}
                >
                  INFO
                </button>
                <button
                  disabled={isFetching}
                  onClick={changeLevel(logger.name, 'WARN')}
                  className={getClassName(logger.level, 'WARN', 'warning')}
                >
                  WARN
                </button>
                <button
                  disabled={isFetching}
                  onClick={changeLevel(logger.name, 'ERROR')}
                  className={getClassName(logger.level, 'ERROR', 'danger')}
                >
                  ERROR
                </button>
                <button
                  disabled={isFetching}
                  onClick={changeLevel(logger.name, 'OFF')}
                  className={getClassName(logger.level, 'OFF', 'secondary')}
                >
                  OFF
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default LogsPage;

// src/main/webapp/app/admin/logs/logs.component.ts
import { Component, OnInit } from '@angular/core';
import { finalize} from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule } from '@angular/forms';
import { SortDirective, SortByDirective } from 'app/shared/sort';
import { Log, LoggersResponse, Level } from './log.model';
import { LogsService } from './logs.service';

@Component({
  standalone: true,
  selector: 'jhi-logs',
  templateUrl: './logs.component.html',
  imports: [SharedModule, FormsModule, SortDirective, SortByDirective],
})
export default class LogsComponent implements OnInit {
  loggers?: Log[];
  filteredAndOrderedLoggers?: Log[];
  isLoading = false;
  filter = '';
  orderProp: keyof Log = 'name';
  ascending = true;

  constructor(private logsService: LogsService) {}

  ngOnInit(): void {
    this.findAndExtractLoggers();
  }

  changeLevel(name: string, level: Level): void {
    this.logsService.changeLevel(name, level).subscribe(() => this.findAndExtractLoggers());
  }


  filterAndSort(): void {
    this.filteredAndOrderedLoggers = this.loggers!.filter(
      logger => !this.filter || logger.name.toLowerCase().includes(this.filter.toLowerCase())
    ).sort((a, b) => {
      if (a[this.orderProp] < b[this.orderProp]) {
        return this.ascending ? -1 : 1;
      } else if (a[this.orderProp] > b[this.orderProp]) {
        return this.ascending ? 1 : -1;
      } else if (this.orderProp === 'level') {
        return a.name < b.name ? -1 : 1;
      }
      return 0;
    });
  }

  private findAndExtractLoggers(): void {
    this.isLoading = true;
    this.logsService
      .findAll()
      .pipe(
        finalize(() => {
          this.filterAndSort();
          this.isLoading = false;
        })
      )
      .subscribe({
        next: (response: LoggersResponse) =>
          (this.loggers = Object.entries(response.loggers).map(([key, logger]) => new Log(key, logger.effectiveLevel))),
        error: () => (this.loggers = []),
      });
  }

}

@if (loggers) {
<div class="table-responsive">
  <h2 id="logs-page-heading" data-cy="logsPageHeading">Logy</h2>


@if (isLoading) {
  <div class="float-end me-3">
    <div class="spinner-border"></div>
  </div>
}

  <p>Spuštěných {{ loggers.length }} loggerů.</p>

  <span>Filtrovat</span>
  <input type="text" [(ngModel)]="filter" (ngModelChange)="filterAndSort()" class="form-control" />

  <table class="table table-sm table-striped table-bordered" aria-describedby="logs-page-heading">
    <thead>
      <tr jhiSort [(predicate)]="orderProp" [(ascending)]="ascending" (sortChange)="filterAndSort()">
        <th jhiSortBy="name" scope="col"><span>Název</span> <fa-icon icon="sort"></fa-icon></th>
        <th jhiSortBy="level" scope="col"><span>Úroveň</span> <fa-icon icon="sort"></fa-icon></th>
      </tr>
    </thead>

    <tbody>
    @for (logger of filteredAndOrderedLoggers; track $index) {
      <tr>
        <td>
          <small>{{ logger.name | slice: 0:140 }}</small>
        </td>
        <td>
          <button
            (click)="changeLevel(logger.name, 'TRACE')"
            [ngClass]="logger.level === 'TRACE' ? 'btn-primary' : 'btn-light'"
            class="btn btn-sm"
          >
            TRACE
          </button>

          <button
            (click)="changeLevel(logger.name, 'DEBUG')"
            [ngClass]="logger.level === 'DEBUG' ? 'btn-success' : 'btn-light'"
            class="btn btn-sm"
          >
            DEBUG
          </button>

          <button
            (click)="changeLevel(logger.name, 'INFO')"
            [ngClass]="logger.level === 'INFO' ? 'btn-info' : 'btn-light'"
            class="btn btn-sm"
          >
            INFO
          </button>

          <button
            (click)="changeLevel(logger.name, 'WARN')"
            [ngClass]="logger.level === 'WARN' ? 'btn-warning' : 'btn-light'"
            class="btn btn-sm"
          >
            WARN
          </button>

          <button
            (click)="changeLevel(logger.name, 'ERROR')"
            [ngClass]="logger.level === 'ERROR' ? 'btn-danger' : 'btn-light'"
            class="btn btn-sm"
          >
            ERROR
          </button>

          <button
            (click)="changeLevel(logger.name, 'OFF')"
            [ngClass]="logger.level === 'OFF' ? 'btn-secondary' : 'btn-light'"
            class="btn btn-sm"
          >
            OFF
          </button>
        </td>
      </tr>
    }
    </tbody>
  </table>
</div>
}
